FROM node:18-alpine

WORKDIR /app

COPY revcart/frontend/package*.json ./
RUN npm install

COPY revcart/frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=0 /app/dist/revcart /usr/share/nginx/html
COPY revcart/frontend/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]